### ISSUE TITLE
Some way of telling visual-fill-column-mode to ignore some lines

### ISSUE THREAD

**Issue by vikasrawal** [joostkremers/visual-fill-column#11]
I would like to use visual-fill-column-mode with my org mode files. However, this has a peculiar problem that org tables also start wrapping at fill-column. Would it be possible to tell visual-fill-column-mode to ignore lines starting with a |?

Or more generally, using a regex to tell visual-fill-column-mode to skip wrapping some lines.

**Comment by joostkremers** [comment]
> Or more generally, using a regex to tell visual-fill-column-mode to skip wrapping some lines.

No, unfortunately, that is fundamentally impossible. `visual-fill-column-mode` does not really do any filling / wrapping. Basically, it just sets the margin to a value such that the text area (i.e., the part of the window that can display text) is narrowed to `fill-column`. So there's simply no way to disable wrapping for certain lines.
