### ISSUE TITLE
visual-fill-column breaks horizontal window splitting on emacs 25

### ISSUE THREAD

**Issue by glyph** [joostkremers/visual-fill-column#13]
I'm using Emacs 25.0.50.1.

1. Start emacs.
2. M-x visual-fill-column-mode
3. `C-x 3`

I would expect the window to split vertically; instead, I get `split-window: Window #<window 3 on *scratch*> too small for splitting (2)`.

As I recall this worked at some point either on an earlier version of Emacs or an earlier version of visual-fill-column.

**Comment by glyph** [comment]
Yeah, just confirmed that it works fine on `GNU Emacs 24.5.1`, so this is only a bug in unreleased versions of Emacs.  So it's probably an emacs issue.  But I don't know how to report it in emacs, so hopefully with better knowledge of visual-fill-column you can write up a bug report for them before they cut the next release :)

**Comment by joostkremers** [comment]
Yeah, something seems to have changed... I'll investigate and see what I can find out.

**Comment by glyph** [comment]
Thanks!

**Comment by joostkremers** [comment]
Do you happen to know when you last updated your Emacs sources before this problem appeared? I'm looking for the last commit where window splitting still worked.

**Comment by glyph** [comment]
Unfortunately I don't update in small increments. Pretty sure I had a build from the beginning of December that didn't have this problem, but I don't think I can be more granular than that.  Sorry, thanks for investigating this, and good luckQ!

**Comment by joostkremers** [comment]
I found the commit that is responsible for this change and asked on emacs-devel. Apparently, it is a planned change, so this is going to be the default behaviour in the next version. I was given some suggestions on how to deal with this on the list, but I haven't gotten round to implementing one yet. I'll post an update here when I do.

**Comment by glyph** [comment]
@joostkremers bummer! I hope you can figure something out before the release, writeroom-mode is one of my favorite emacs packages :)

**Comment by joostkremers** [comment]
I've implemented the suggested fix, and it seems to work. Please try it and let me know if you run into any problems.

**Comment by glyph** [comment]
@joostkremers Just wanted to follow up and say: yes, it seems to work great, I've been using various versions and platforms of Emacs 25 for a while, and it seems like everything's working smoothly when I invoke writeroom-mode :)

**Comment by joostkremers** [comment]
Thanks for letting me know. Glad to hear it's working fine. :
