### ISSUE TITLE
visual-fill-column-split-window-sensibly should autoload

### ISSUE THREAD

**Issue by wbolster** [joostkremers/visual-fill-column#15]
my `init.el` contains

```elisp
(setq split-window-preferred-function 'visual-fill-column-split-window-sensibly)
```

...but that function is undefined unless i explicitly `(require 'visual-fill-column)`, or enable `writeroom-mode` which implicitly causes the package to be loaded. i believe this causes the window splitting routines to not work as expected on startup.

i guess the solution is to mark the function with `autoload`.

**Comment by joostkremers** [comment]
Yeah, I guess autoloading makes sense. I never ran into the issue myself, even though I `visual-fill-column-mode` isn't loaded explicitly in my init file. I guess there's some file-loading chain in my init file that ends up loading `visual-fill-column-mode`...

**Comment by wbolster** [comment]
awesome, thanks.
