### ISSUE TITLE
Option to wrap words

### ISSUE THREAD

**Issue by ChillarAnand** [joostkremers/visual-fill-column#18]
![vv](https://cloud.githubusercontent.com/assets/4463796/15996938/40049d50-314b-11e6-908c-1d7cd45fc76f.png)

When there is a word at the end which can't fit, can the word be moved to next line? Otherwise it is much harder while reading.

**Comment by joostkremers** [comment]
That's what `visual-line-mode` is for. `visual-fill-column` is usually used in combination with it.

**Comment by ChillarAnand** [comment]
writeroom-mode is using this package as dependency. I don't know about it.  Thank you :-)

**Comment by joostkremers** [comment]
Hmm, good point. Perhaps I should mention something about `visual-line-mode` or line wrapping in general in the documentation to `writeroom-mode`.

**Comment by ChillarAnand** [comment]
:+1:
