### ISSUE TITLE
mu4e headers issue

### ISSUE THREAD

**Issue by emacsomancer** [joostkremers/visual-fill-column#20]
For some reason, if I use visual-fill-column anywhere in emacs, then if I leave mu4e-headers open in a buffer then visual-fill-column gets applied to that buffer. It doesn't happen immediately, but only after about 5-10 minutes, and I have to redraw or switch buffers for it to be restored.

**Comment by joostkremers** [comment]
I'll assume that this is the same issue as #21, so hopefully a single solution can be found.

Could you tell me which Emacs version you're running and how you activate `visual-fill-column`? Do you use `global-visual-fill-column-mode` or do you use mode hooks? Do you use `visual-line-mode` and if yes, how do you activate it?

**Comment by emacsomancer** [comment]
I was activating visual-fill-column using mode hooks. I was also using visual-line-mode, and also activating it via mode hooks (the same hooks for both, in fact). 

I'm running Emacs 25.1.1.

I tried the similar emacs package window-margin-mode, and I get exactly the same issues. If that helps at all.

**Comment by joostkremers** [comment]
I've been trying to reproduce your issue by leaving the `*mu4e-headers*` buffer open, but so far I haven't seen any problems. So all I can do is ask more questions and hope that one of them will give me a clue. So I'd appreciate it if you could answer the following:
 
Could you show me the part of your config that are relevant to `visual-fill-column`?

Can you check if `visual-line-mode` is active in  the `*mu4e-headers*` and `*elfeed-search*` buffers when the problem occurs?

What exactly is your workflow when this happens? You open `*mu4e-headers*`, do your thing, move to another window with `C-x o`? Do you move to another frame? Does the window holding the `*mu4e-headers*` buffer get split and unsplit? Does resizing the window also solve the issue, or do you really need to switch buffers or redisplay?

**Comment by emacsomancer** [comment]
This is what the `visual-fill-column` config stuff looks like:

`;; visual-fill-column
(use-package visual-fill-column
  :ensure t
  )
(add-hook 'LaTeX-mode-hook 'visual-line-mode)
(add-hook 'LaTeX-mode-hook 'visual-fill-column-mode)
(add-hook 'org-mode-hook 'visual-line-mode)
(add-hook 'org-mode-hook 'visual-fill-column-mode)
(add-hook 'mu4e-view-mode-hook 'visual-line-mode)
(add-hook 'mu4e-view-mode-hook 'visual-fill-column-mode)
(add-hook 'mu4e-compose-mode-hook 'visual-line-mode)
(add-hook 'mu4e-compose-mode-hook 'visual-fill-column-mode)
(add-hook 'elfeed-show-mode-hook 'visual-line-mode)
(add-hook 'elfeed-show-mode-hook 'visual-fill-column-mode)`

Today I'm trying just turning on the hooks for mu4e and not any of the other modes. I'm wondering if there's some weird interaction between `mu4e`, `elfeed`, and`visual-fill-column-mode`.

In my workflow, I could open open mu4e, leave a buffer open with `mu4e-headers` (which looked fine), walk away from the machine for 10 minutes and when I got back I found the odd behaviour I described in the first post.

I'll try different combinations to try to find the minimal setup that causes this issue.  Do you use `elfeed` at all?

**Comment by joostkremers** [comment]
> In my workflow, I could open up mu4e, leave a buffer open with `mu4e-headers` (which looked fine), walk away from the machine for 10 minutes and when I got back I found the odd behaviour I described in the first post.

So you're not interacting with Emacs at all when this happens. I know  the `mu4e-headers` buffer is updated from time to time, which is the only thing that I can think of that can suddenly turn on `visual-fill-column-mode`. (Though I can't really understand **how** it could happen...)

If the problem reoccurs, could you do `C-h v visual-fill-column-mode RET` (while the `mu4e-headers` buffer is selected)? The second line of the help buffer should tell you what the variable's value is. If it is `t`, then `visual-fill-column-mode` is really active. If it is `nil`, then there's some display glitch (which is probably unlikely, but I'd like to rule it out anyway).

And while you're at it, could you do `C-h v visual-line-mode RET` as well? If `visual-fill-column-mode` is turned on through some hook, `visual-line-mode` should also be on, because it's in the same hooks.

> I'll try different combinations to try to find the minimal setup that causes this issue.

Any info you could provide would be helpful, because I'm still mystified...

> Do you use elfeed at all?

No, that's why I've been focusing on mu4e, which I do use. I'm hoping it's the same problem. And I'm hoping that the issue doesn't depend on elfeed.

**Comment by emacsomancer** [comment]
Ok, so the following seems to work without problem, at least for the past day:

`(add-hook 'LaTeX-mode-hook 'visual-line-mode)`
`(add-hook 'LaTeX-mode-hook 'visual-fill-column-mode)`
`(add-hook 'org-mode-hook 'visual-line-mode)`
`(add-hook 'org-mode-hook 'visual-fill-column-mode)`
`(add-hook 'mu4e-view-mode-hook 'visual-line-mode)`
`(add-hook 'mu4e-view-mode-hook 'visual-fill-column-mode)`

So I suspect whatever was going on before is some sort of interaction between `mu4e`, `elfeed`, and `visual-fill-column-mode`. 

I still get the same behaviour I mentioned with `elfeed` itself if I enable:

`(add-hook 'elfeed-show-mode-hook 'visual-line-mode)`
`(add-hook 'elfeed-show-mode-hook 'visual-fill-column-mode)`

Oddly, it seems that I can manually turn on `visual-fill-column-mode` for an `elfeed-show` buffer without triggering this effect, but not with the hook.
