### ISSUE TITLE
Doesn't resize margin when resizing the frame

### ISSUE THREAD

**Issue by lunaryorn** [joostkremers/visual-fill-column#23]
When I resize the frame on OS X the margins don't change, even if I toggle Visual Fill Column Mode or switch to a different buffer.

How could I debug this?  I'm not quite familiar with margins.

**Comment by joostkremers** [comment]
> How could I debug this? I'm not quite familiar with margins.

Hmm... I'm on Linux and resizing the Emacs frame adjusts the margins.

The margins are adjusted in the function `visual-fill-column--adjust-window`, which is run from `window-configuration-change-hook`, and also when `v-f-c-mode` is activated.

`visual-fill-column--adjust-window` is one of the functions I modified in order to fix bug #22. One thing you might try is to add some `message` calls to this function, to see if it's actually called or not. If it is, you can try and figure out why it gets called but doesn't change the margins.

Furthermore, the margins are also set in `visual-fill-column-split-window` and `visual-fill-column-split-window-sensibly`, but I don't know if you use these. (You only use them if you've set `split-window-preferred-function` to `visual-fill-column-split-window-sensibly`. `v-f-c-mode` doesn't do this.)

Anyway, that's where I would start.

**Comment by LindyBalboa** [comment]
I'm on Arch Linux using i3 and this is an issue for me too. I will take a look through your suggestions later @joostkremers.

**Comment by LindyBalboa** [comment]
Hm. It turns out if I do an M-x it forces a window redraw and then the margin adjusts. 

Seems in Emacs 26+ `window-size-change-functions` could be a solution.

**Comment by LindyBalboa** [comment]
I also experience freezing with 100% CPU usage when changing the frame size. This is definitely tied to this package somehow. Any suggestions how to get some debug info on this behavior?

**Comment by LindyBalboa** [comment]
Readjusting works if I call `visual-fill-column--adjust-window` manually. Seems to be a problem with how the hook is calling it.

**Comment by joostkremers** [comment]
I'm currently using Emacs 25, could well be that some things changed in 26. I'll have to check that out, but I'm quite busy at the moment, so it might take some time.

**Comment by LindyBalboa** [comment]
From the changelog:
```
*** Resizing a frame no longer runs 'window-configuration-change-hook'.
'window-size-change-functions' should be used instead.

+++
*** The new function 'frame-size-changed-p' can tell whether a frame has
been resized since the last time 'window-size-change-functions' has been
run.
```

Useful info:

```Lisp programs that need to know how much screen estate is used up for
line-number display in a window can use the new function
'line-number-display-width'.
```

**Comment by LindyBalboa** [comment]
The quick fix is this line: `(setq window-size-change-functions '(visual-fill-column-adjust))`. Someone with better elisp than me should add a line making this to append instead of override, and add it to the `--enable` function. (May take a look tomorrow afternoon if nobody beats me to it).

**Comment by plantarum** [comment]
I ran into this today, changing the frame size lead to Emacs hanging / pegging the CPU at 100%. Turning off visual-fill-column-mode fixed the problem, and the solution provided by @LindyBalboa seems to work. I've implemented it as follows:

    (defun visual-fill-column-mode--enable ()
      "Set up `visual-fill-column-mode' for the current buffer."
      (add-to-list 'window-size-change-functions #'visual-fill-column-adjust)
      (visual-fill-column--adjust-window))
    
    
    (defun visual-fill-column-mode--disable ()
      "Disable `visual-fill-column-mode' for the current buffer."
      (setq window-size-change-functions
            (delete #'visual-fill-column-adjust window-size-change-functions))
      (set-window-fringes (get-buffer-window (current-buffer)) nil)
      (set-window-margins (get-buffer-window (current-buffer)) nil))
    
Seems to be working after some very limited testing. I'm not sure what this might interact with in visual-fill-column-mode, so this may have introduced new problems :/

GNU Emacs 26.0.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.24) of 2017-12-21

**Comment by plantarum** [comment]
Six hours later, my previous code proves to be inadequate. Still no more freezes, but there are regular moments when Emacs 'forgets' visual-fill-column, and the text stretches all the way across the screen. Manually calling `(visual-fill-column-adjust)` cleans it up, but clearly more needs to be done to update the mode for Emacs 26 than what I suggested.

**Comment by noctuid** [comment]
This is somewhat related, but I've had the same issue even when not resizing the frame. Having `visual-fill-column--adjust-window` in `window-configuration-change-hook` consistently freezes emacs when using [zoom-mode](https://github.com/cyrus-and/zoom) with multiple windows of the same file open (e.g. `split-window-horizontally` in file then `other-window`; `pkill -SIGUSR2 emacs` sometimes works).

**Comment by stettberger** [comment]
You probably have to call `(set-window-buffer nil (current-window)` every time you update the margins.

**Comment by joostkremers** [comment]
I closed this issue because I assume it's been fixed. In Emacs 26, `visual-fill-column--adjust-window` is added to `window-size-change-functions`, which turned out to be needed because `window-configuration-change-hook` is called in fewer situations in Emacs 26.

**Comment by surchs** [comment]
I can confirm that this is still an issue under `GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)` and `visual-fill-column` version `Version: 20201229.230` from melpa:
![line-reflow](https://user-images.githubusercontent.com/1302022/104392574-5b07af00-5510-11eb-9080-64fcb3d37c6b.gif)
