### ISSUE TITLE
Improper line break for Chinese characters

### ISSUE THREAD

**Issue by jlhg** [joostkremers/visual-fill-column#24]
For Chinese-English mixed article, some lines break at the improper position. Here is the example:

<img width="809" alt="2017-01-03 15 30 23" src="https://cloud.githubusercontent.com/assets/2265716/21601913/3ff4b94c-d1ca-11e6-8913-1364a4ed4e1e.png">

**Comment by joostkremers** [comment]
`visual-fill-column-mode` doesn't change anything about the line breaking algorithms, it only narrows the margin. You'll probably see the same effect if you narrow the window (or the frame containing the window) without using `visual-fill-column-mode`.

So I believe this should probably be reported as an Emacs bug. If you do report it, best to leave out `visual-fill-column-mode` and demonstrate the problem using window or frame width.

**Comment by jlhg** [comment]
I will report it as an Emacs bug. Thanks.
