### ISSUE TITLE
Have visual-fill-column ignore org-mode headings?

### ISSUE THREAD

**Issue by wildgruber** [joostkremers/visual-fill-column#31]
Hello,

is it possible to have visual-fill-column's line wrapping mechanism ignore org-mode headings?

I'm using visual-line mode together with visual-fill-column and writeroom-mode (thanks for this great package too!) and I would prefer org-mode headings not to be wrapped at all, as I think it doesn't look good and really breaks the clean look of a collapsed org-mode file.

Instead headings longer than fill-column could just run all the way to window margin and their continuation, if necessary, be indicated by a little arrow (as is often the case in emacs).

Thanks

Gerald.

**Comment by joostkremers** [comment]
Unfortunately, that is not possible. `visual-fill-column-mode` widens the margins in order to make the text wrap at `fill-column`, and the margins cannot contain editable text. So it's really an all-or-nothing thing: either you wrap everything, or you wrap nothing.

**Comment by wildgruber** [comment]
Ah, OK I see: thanks for clarifying this!

Gerald
