### ISSUE TITLE
Change the window size in Emacs 26.1 can't resized

### ISSUE THREAD

**Issue by HomelandScenery** [joostkremers/visual-fill-column#32]
I encountered some problems in changing the window. In version 25.3, it is normal, but the problem in the picture that appears in 26.1. Please help.
![25 3](https://user-images.githubusercontent.com/19407813/42741339-dc89067e-88e3-11e8-9fa2-45a83d7e4320.png)
![25 3-resize](https://user-images.githubusercontent.com/19407813/42741342-e2e9128e-88e3-11e8-911f-3f261024271e.png)

While in 26.1 used emacs -q

![26 1-emacs-q](https://user-images.githubusercontent.com/19407813/42740940-1cfb6d0e-88e0-11e8-8828-b05969109be4.png)
![26 1-resize1](https://user-images.githubusercontent.com/19407813/42740944-24bf6022-88e0-11e8-9c00-09bf90bae4c4.png)
Thank you!

GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-13

GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30

**Comment by joostkremers** [comment]
Could you give a precise recipe that shows the problem? To which Emacs versions do the screenshots belong?

**Comment by HomelandScenery** [comment]
Please forgive my expression.
The two picture **above is the 25.3 version**. The text is located in the middle. Even after the window is adjusted, I think it is normal.
The two picture **below is the 26.1 version**. After the window is adjusted, the text is compressed in a very narrow space.
Thank you!

**Comment by joostkremers** [comment]
Hi, sorry for the late reply. As it turns out, there has been a change in Emacs 26 that causes this behaviour. I'll need to figure out how to solve it.

Thanks for bringing this to my attention.

**Comment by joostkremers** [comment]
I just pushed a fix for this, which seems to do the trick. Please test it and let me know if you run into further trouble.

**Comment by HomelandScenery** [comment]
Thank you very much for your solution.

It feels good now.😊😊😊
