### ISSUE TITLE
Margins do not compensate for line numbers

### ISSUE THREAD

**Issue by elecprog** [joostkremers/visual-fill-column#37]
`display-line-numbers-mode` draws the line numbers in the buffer, currently visual fill column does not take this into consideration which results in shorter lines than configured. Unfortunately there is no real workaround on the user side as the width of the line number column dynamically scales.

I don't know how bad the drawbacks are of using `(display-line-numbers-update-width)`, it does seem to prevent the line number column from shrinking, and it only returns the number of characters in the line number when that number actually changes (also in the default configuration there are 2 more characters added as padding so that has to be taken into account as well unfortunately).

On how to change the margins, there are two main options there I think:

1. The most elegant solution I think would be to subtract the line number column width from the right margin, when centreing is disabled and when centreing is enabled it should be subtracted from the left.

2. But it would probably be easier to simply add line number column width to the text width as this would add less edge cases, however the buffer would not be centred as nicely, IMHO.

By the way, thanks for this amazing plugin :slightly_smiling_face:

**Comment by manuel-uberti** [comment]
I just saw [this commit](https://github.com/joostkremers/visual-fill-column/commit/c8d61f0287636a23b01fdc6e120cfeb9eb460107). Does it fix the problem for you?

**Comment by elecprog** [comment]
Unfortunately not, `display-line-numbers-width` is a configuration variable which sets the minimum width of the number column (which can grow beyond this value), by default it's nil which means that the minimum width is to be determined dynamically.

**Comment by joostkremers** [comment]
The doc string mentions that `display-line-number-width` becomes buffer-local when set, and a quick test suggested that in a buffer in which `display-line-number-mode` is active, this variable is set to the width of the line number column.

**Comment by joostkremers** [comment]
> I just saw [this commit](https://github.com/joostkremers/visual-fill-column/commit/c8d61f0287636a23b01fdc6e120cfeb9eb460107). Does it fix the problem for you?

This commit was wrong, as I found out recently. I've now changed it [here](https://github.com/joostkremers/visual-fill-column/commit/5f5d816b5c2a2175d66e6aef7e27b1efa50ab3aa). Hopefully this time I got it right. :slightly_smiling_face:
