### ISSUE TITLE
Keep fringes

### ISSUE THREAD

**Issue by manuel-uberti** [joostkremers/visual-fill-column#4]
I put ```setq visual-fill-column-fringes-outside-margins nil``` in my init.el, but fringes are not visible when ```visual-fill-column``` is active. Problem is I need fringes because I am using [diff-hl](https://github.com/dgutov/diff-hl) to highlight uncommited changes in my buffers.

Is there some other setting I could use?

I am using Emacs ```25.0.50.1``` on ```Debian``` unstable.

**Comment by joostkremers** [comment]
`visual-fill-column-mode` doesn't touch the fringes themselves, only their position, so you should still see them. It works for me when I set `visual-fill-column-fringes-outside-margins` to `nil`, so I don't really understand why they disappear in your case...

**Comment by manuel-uberti** [comment]
I see, but when I disable ```visual-fill-column``` in a buffer where ```diff-hl``` is enabled, fringes appear again and I can see ```diff-hl``` indicators.

**Comment by manuel-uberti** [comment]
Actually, debugging a bit further I found the problem is with ```diff-hl```. Do not mind this issue, then.

**Comment by manuel-uberti** [comment]
Still debugging on this one. If I disable this hook in my configuration:
```
(add-hook 'visual-line-mode-hook #'visual-fill-column-mode)
```
But keep using ```visual-line-mode```, such as this:
```
(add-hook 'markdown-mode-hook #'visual-line-mode)
```
Fringes don't disappear and ```diff-hl``` indicators are visible. So I have to understand if ```visual-fill-column-mode``` conflicts with ```diff-hl``` or viceversa.

**Comment by manuel-uberti** [comment]
The problem is in ```visual-fill-column-mode```.
This is what I did:
- disabled the hook on ```visual-line-mode```: ```;; (add-hook 'visual-line-mode-hook #'visual-fill-column-mode)```
- enabled ```diff-hl``` globally: ```(global-diff-hl-mode)```
- edited an *.el file which I know is under ```diff-hl``` control
- enabled ```visual-line-mode```: fringes are there, ```diff-hl``` indicators too
- closed the file, enabled back ```visual-fill-column``` hook on ```visual-line-mode```
- opened the previous file: fringes are gone

**Comment by joostkremers** [comment]
I don't seem to be able to reproduce this with Emacs 24.4.1, nor with 25.0.50.2. Have you tried with `emacs -Q`?

What happens if you use `(global-visual-fill-column-mode)` instead of adding `visual-fill-column-mode` to `visual-line-mode-hook`? Same thing?

**Comment by manuel-uberti** [comment]
With ```emacs -Q``` using ```(global-diff-hl-mode)``` and ```(global-visual-fill-column-mode)``` work fine.

If I use ```(global-visual-fill-column-mode)``` instead of the hook in ```emacsclient``` does not work.

**Comment by manuel-uberti** [comment]
One thing though: with the hook on ```visual-line-mode``` and ```(global-diff-hl-mode)``` active, it is working if I don't use ```emacsclient``` and ```emacs --daemon``` but simply ```emacs```. Weird.

**Comment by joostkremers** [comment]
I'm afraid I can't even reproduce it with `emacsclient` (though I don't use `emacs --daemon`, I run `(server-start)` in my init file). However, if it depends on the way Emacs is started, perhaps you should file a bug for Emacs?

**Comment by manuel-uberti** [comment]
Ok, you can consider this issue close then. Thanks for the help and for the awesome package.

**Comment by FrancescoCadei** [comment]
Same problem here

**Comment by FrancescoCadei** [comment]
Solved with `(add-hook 'visual-fill-column-mode-hook 'diff-hl-margin-mode)`.
