### ISSUE TITLE
Behavior like fill-paragraph with prefix argument (C-u)

### ISSUE THREAD

**Issue by marcelino-m** [joostkremers/visual-fill-column#41]
It's possible have all line same width?, I mean have similar behavior how when run the command `fill-paragrap` with prefix argument

**Comment by joostkremers** [comment]
Well, `visual-fill-column-mode` doesn't do paragraph filling at all, that's up to Emacs itself. Currently, `visual-line-mode` (which I assume you're using) doesn't have this option, so I'm afraid the answer to your question is no, it's not possible.
