### ISSUE TITLE
Mouse events in right margin

### ISSUE THREAD

**Issue by ThibautVerron** [joostkremers/visual-fill-column#42]
Hi, and thanks for this great package!

I have been using it for years, but I recently added the following bindings to make it more comfortable when occasionally using the mouse, even if only to focus the window.

```
(define-key visual-fill-column-mode-map [right-margin mouse-1] #'mouse-set-point)
(define-key visual-fill-column-mode-map [right-margin mouse-2] #'mouse-popup-menubar-stuff)
(define-key visual-fill-column-mode-map [right-margin mouse-3] #'mouse-yank-primary)
(define-key visual-fill-column-mode-map [right-margin drag-mouse-1] #'ignore)
(define-key visual-fill-column-mode-map [right-margin drag-mouse-2] #'ignore)
(define-key visual-fill-column-mode-map [right-margin drag-mouse-3] #'ignore)
(define-key visual-fill-column-mode-map [right-margin double-mouse-1] #'ignore)
(define-key visual-fill-column-mode-map [right-margin double-mouse-2] #'ignore)
(define-key visual-fill-column-mode-map [right-margin double-mouse-3] #'ignore)
(define-key visual-fill-column-mode-map [right-margin triple-mouse-1] #'ignore)
(define-key visual-fill-column-mode-map [right-margin triple-mouse-2] #'ignore)
(define-key visual-fill-column-mode-map [right-margin triple-mouse-3] #'ignore)
```

Maybe the package could supply them by default?

The first 3 restore the bindings to the default (on my config... there is probably a better way to do that anyway). I was pleasantly surprised to discover that `mouse-set-point` does the right thing.

The rest is just to avoid having a bell whenever one double, triple, or long-clicks in the margin.

**Comment by joostkremers** [comment]
Yes, that certainly makes sense.

> The first 3 restore the bindings to the default (on my config... there is probably a better way to do that anyway).

It might be nice to bind these to the same events that the user has bound to [mouse-{123}] automatically, but I can't find an easy way of doing that. I'll ask on the Emacs mailing list if there's anyone who knows.

**Comment by joostkremers** [comment]
> It might be nice to bind these to the same events that the user has bound to [mouse-{123}] automatically,

Turns out that wasn't too difficult. The binding should now work automatically, without you having to replicate them specifically for `visual-fill-column-mode`. Do let me know if that is not the case, though.

Thanks for suggesting these key bindings!

**Comment by ThibautVerron** [comment]
Thanks!

As long as mouse events are bound before loading the package, it seems to be working.

**Comment by joostkremers** [comment]
> As long as mouse events are bound before loading the package, it seems to be working.

Yes, that makes sense. I use `global-key-binding` to find out what the user has `mouse-[123]` bound to, to replicate that in the margins. So if you customise your mouse bindings, you need to load `visual-line-mode` after that, or the default bindings will be used.

If you use `use-package`, you can use the `:after` keyword in your config. Otherwise you need to take care of the order of loading.

Perhaps it would be better to always use Emacs' default mouse events and have the user configure them explicitly. That would certainly make things more transparent.
