### ISSUE TITLE
Indent lines?

### ISSUE THREAD

**Issue by contrapunctus-1** [joostkremers/visual-fill-column#43]
Hi, thank you very much for writing visual-fill-column-mode!

I had a feature request and I couldn't find any existing issue about it. Could visual-fill-column-mode be extended to indent lines? e.g.

```
1. A very long line
that gets wrapped around
```

Becoming
```
1. A very long line
   that gets wrapped around
```

It'd make it a lot cleaner-looking, to my eyes.

**Comment by joostkremers** [comment]
This is not something `visual-fill-column-mode` was designed to do. It's up to the major mode to do this. In Org mode, it works correctly for me.

**Comment by contrapunctus-1** [comment]
@joostkremers could you please say how one might reproduce that? Starting Emacs with -q, and using Org mode + visual-fill-column does not give me this behaviour 🤔 And the only way I've found so far is to use visual-fill-column in conjunction with adaptive-wrap. (The latter by itself will indent lines as I describe above without changing the file, but will only wrap lines if they go past the window, not if they exceed fill-column)

**Comment by joostkremers** [comment]
In Markdown files, `adaptive-wrap-prefix-mode` does this, in Org files, I use `org-indent-mode` (and I disable `adaptive-wrap-prefix-mode`), which does the same thing and more.

If I disable `org-indent-mode` and enable `adaptive-wrap-prefix-mode` in an Org buffer, I get the effect you desire, though, so I guess it should work.

I did make a small change to the default value of `adaptive-fill-regexp`, but I don't think that would make a difference.

**Comment by contrapunctus-1** [comment]
Thanks for telling me about org-indent-mode - I didn't know about it, it's very cool! I guess this issue can be closed?

**Comment by joostkremers** [comment]
> Thanks for telling me about org-indent-mode - I didn't know about it, it's very cool!

You're welcome. Glad it's useful. :smiley:

> I guess this issue can be closed?

I'll close it.
