### ISSUE TITLE
inline images in org-mode are cropped by visual-fill-column-mode

### ISSUE THREAD

**Issue by japhir** [joostkremers/visual-fill-column#45]
Hi! Thanks for the excellent package! It has helped me put the main content right in the centre of the page and has been very helpful for writing.

I write in org-mode, and often have inline images turned on. Some of those images are quite wide, and are currently cropped by visual-fill-column. Would it be possible to make images somehow always centred and display fully? That would make this mode even better :).

Kind regards

**Comment by joostkremers** [comment]
I've done some searching, but I haven't found anything about automatically resizing images. There is `org-image-actual-width`, which you can use to influence an image's width, but it's not entirely automatic, and it's not something `visual-fill-column-mode` could do automatically.

I'll search some more and if I find something, I'll let you know.

**Comment by terlar** [comment]
I wonder if there could be some relative content here:
https://lists.gnu.org/archive/html/emacs-orgmode/2019-12/msg00030.html

I think what is missing is an `org-image-actual-width` that takes current window width into account, preferably only if the image is larger.

**Comment by joostkremers** [comment]
The tools to make something like this work definitely seem to be available. Emacs supports `:height` and `:width` and `:max-height` and `:max-width` attributes for images, but they must be set when the image is defined. So when the window margins are changed, one would have to go through the buffer and adjust all images. Or perhaps that is something that can be done when an image moves into the visible part of a buffer, I don't know.

Still, it would be a fair bit of work, and though I agree it would be nice to have, I can't promise anything.

**Comment by nmartin84** [comment]
So I think you could use  `(window-text-pixel-size)` to return the size in pixels for whatever your fill-column size is, and then return that value back to `org-image-actual-width`.

However if the current `window-pixel-width` is less than that value, then you'll be truncated again. But you could add a condition that if org-image-actual-width is greater than `window-pixel-width`, then set it to something like this: `org-image-actual-width (truncate (* (window-pixel-width) 0.90))`.

**Comment by joostkremers** [comment]
I'm moving this repo over to [Codeberg](https://codeberg.org/joostkremers/visual-fill-column) so I'm closing this issue. I've replicated it at https://codeberg.org/joostkremers/visual-fill-column/issues/2 to make sure it's not forgotten.
