### ISSUE TITLE
Window too small for splitting error

### ISSUE THREAD

**Issue by farynaio** [joostkremers/visual-fill-column#49]
I get "Window <X> too small for splitting" error while I try to split full screen window. Is there any solution for this?

Turning on and off visual-fill-column-mode for current buffer helps temporarily.

**Comment by joostkremers** [comment]
Yes, I've run into this issue myself several times, but I have not been able to find out what causes it. What version of Emacs are you using? When a window cannot be split, could you check the values of the window parameters `split-window` and `min-margins`? E.g.:

    M-: (window-parameter nil 'split-window)

and 

    M-: (window-parameter nil 'min-margins)

**Comment by farynaio** [comment]
Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7.

I will check these values next time I will stumble upon this.

**Comment by farynaio** [comment]
I ended up quiting `visual-fill-column` for the moment. Maybe somebody else will stumble upon this.

**Comment by joostkremers** [comment]
I will post here if I find a solution. Hopefully I'll have some time to look into this next week.

**Comment by dangom** [comment]
Funny. I never had this issue before but just updated to Emacs 28 / native comp and getting this issue now. It doesn't seem like it's always reproducible. Sometimes turning on and off visual fill column will solve it.
Nonetheless, here's a hackish workaround. Bind it to C-x 3 if you may:

```elisp
(defun hack-split-window-right ()
  (interactive)
  (with-temp-buffer
    (split-window-right)))

```

**Comment by joostkremers** [comment]
@dangom Thanks for that workaround. I agree it's hackish. :disappointed: I've run into this issue myself again and the cause that the `min-margins` window parameter is not set correctly. Unfortunately, I haven't been able to figure out how that happens. The only way this might happen is when `visual-fill-column-mode--enable` is called in a buffer in which `visual-fill-column-mode` is already active.

The only way that could happen, though, is if `visual-fill-column-mode` is called in a buffer in which the mode is already active.

I have pushed a commit that should prevent `min-margins` from getting a value that makes splitting impossible. I would appreciate it if you could update `visual-fill-column-mode` (the update should appear on Melpa soon) and let me know if you keep running into the problem. Then hopefully I won't hear from you again. :smile:

**Comment by japhir** [comment]
I ran into this issue as well on emacs 27.2 with 
```
visual-fill-column 20210323.2039 installed             fill-column for visual-line-mode
```

I have it enabled in all org buffers by hooking from `org-mode` to `visual-line-mode` to `visual-fill-column-mode`. It is especially annoying when annotating a pdf with org-noter and not being able to resize the noter org file. If I disable and re-enable the mode everything seems to work fine.

**Comment by joostkremers** [comment]
@japhir Could you check the `min-margins` window parameter when this happens:

    M-: (window-parameter nil 'min-margins)

Could you also try running with `debug-on-error` set to `t` (`M-x toggle-debug-on-error`), and copy & paste the backtrace Emacs spits out when splitting goes wrong? That could be helpful in diagnosing the problem, because I haven't run into the issue myself since the last fix.

**Comment by dangom** [comment]
I haven't come across the issue ever again, so at my end it's "fixed" ( can't prove it isn't, but couple days of testing and all is fine).

**Comment by japhir** [comment]
Ah yep, it seems fixed! Maybe I had updated the package but not restarted my emacs daemon yet. Cheers!

**Comment by joostkremers** [comment]
> Ah yep, it seems fixed! Maybe I had updated the package but not restarted my emacs daemon yet. Cheers!

Whew, that's a relief to hear. :smile: 

Mind you, the fix is really just a stop-gap measure, so I still need to dive into this one day and find out what's really causing it, but at least for now we can all get on with our work.

**Comment by japhir** [comment]
oh no, it's not fixed :(

here's the output of trying to split the window from `toggle-debug-on-error`
```
Debugger entered--Lisp error: (error "Window #<window 3 on one_plan_to_rule_them_all.org...")
  signal(error ("Window #<window 3 on one_plan_to_rule_them_all.org..."))
  error("Window %s too small for splitting" #<window 3 on one_plan_to_rule_them_all.org>)
  split-window(nil nil t)
  split-window-right(nil)
  funcall-interactively(split-window-right nil)
  call-interactively(split-window-right nil nil)
  command-execute(split-window-right)
```

and the output of `M-: (window-parameter nil 'min-margins)`
```
(61 . 62)
```

**Comment by joostkremers** [comment]
Bummer...

But I have identified at least one scenario in which the bug still appears: reverting a buffer in which `visual-fill-column-mode` is enabled. This does not reset the margins, but it does reactivate `visual-fill-column-mode`. The stop gap measure that I introduced doesn't help in this case.

This suggests that any scenario will trigger the bug in which a window's buffer is changed and both the old and the new buffer enable `v-f-c-mode`. (`find-alternate-file` is a case in point and it does indeed trigger the bug.)

This also suggests a possible solution, which I hope to be able to test in the coming days. I will post here once I know more.

**Comment by joostkremers** [comment]
> This also suggests a possible solution, which I hope to be able to test in the coming days. I will post here once I know more.

Unfortunately, the solution I was thinking about isn't working. So in order to solve this issue, I have decided to simply set the `min-margins` window parameter to `(0 . 0)` and not try to restore the original window margins when `v-f-c-mode` is disabled. I'm assuming (hoping?) that few user actually depend on this behaviour, so solving this issue seems preferable to keeping that obscure bit of functionality.

I'm hoping that this fix will finally kill this bug (testing with `revert-buffer` suggests it does), but if the zombie should rise again, do let me know. :zombie:

**Comment by japhir** [comment]
after the update and a fresh reboot this seems to work!

**Comment by joostkremers** [comment]
Whew! :relieved: 

Actually, since I removed the functionality that was the cause of the problem, I'd be very surprised if it still hadn't worked. But then again, it's entirely possible that I overlooked something...

**Comment by hanschen** [comment]
I encounter this issue in combination with [org-roam](https://github.com/org-roam/org-roam) when enabling `visual-fill-column` like this (I use Doom Emacs):

    (add-hook 'org-mode-hook #'visual-fill-column-mode)

It doesn't seem to happen if I enable `visual-fill-column` manually. I suspect it's related to the `org-roam-buffer`, which opens automatically when I use org-roam (see screenshot on `org-roam` page - it's the buffer on the right side with backlinks). If I disable and enable `visual-fill-column`, it works as expected.

Any suggestions on how to fix this? I'm pretty new to Emacs, so it's possible that it's a configuration issue.

When this issue happens:

`M-: (window-parameter nil 'split-window)`

    nil

`M-: (window-parameter nil 'min-margins)`

    (80 . 0)

(after disabling and enabling `visual-fill-column` it becomes `(0 . 0)`)

`toggle-debug-on-error`

```
Debugger entered--Lisp error: (error "Window #<window 3 on 20210303173950-org_mode.org> ...")
  signal(error ("Window #<window 3 on 20210303173950-org_mode.org> ..."))
  error("Window %s too small for splitting" #<window 3 on 20210303173950-org_mode.org>)
  split-window(#<window 3 on 20210303173950-org_mode.org> nil right)
  (select-window (split-window origwin count 'right))
  (let ((doom-inhibit-switch-window-hooks t) (origwin (selected-window))) (select-window (split-window origwin count 'right)) (if evil-vsplit-window-right nil (select-window origwin)) (run-hooks 'doom-switch-window-hook))
  +evil-window-vsplit-a(nil nil)
  apply(+evil-window-vsplit-a (nil nil))
  evil-window-vsplit(nil nil)
  funcall-interactively(evil-window-vsplit nil nil)
  call-interactively(evil-window-vsplit)
  (cond ((not evil-ex-range) (setq this-command evil-ex-command) (run-hooks 'pre-command-hook) (call-interactively evil-ex-command) (run-hooks 'post-command-hook)) (t (let ((ex-range (evil-copy-range evil-ex-range)) beg end) (evil-expand-range ex-range) (setq beg (evil-range-beginning ex-range) end (evil-range-end ex-range)) (let ((sortvar (sort (list beg end) '<))) (setq beg (car-safe (prog1 sortvar (setq sortvar ...))) end (car-safe (prog1 sortvar (setq sortvar ...))))) (setq this-command evil-ex-command) (run-hooks 'pre-command-hook) (set-mark end) (goto-char beg) (activate-mark) (call-interactively evil-ex-command) (run-hooks 'post-command-hook))))
  (unwind-protect (cond ((not evil-ex-range) (setq this-command evil-ex-command) (run-hooks 'pre-command-hook) (call-interactively evil-ex-command) (run-hooks 'post-command-hook)) (t (let ((ex-range (evil-copy-range evil-ex-range)) beg end) (evil-expand-range ex-range) (setq beg (evil-range-beginning ex-range) end (evil-range-end ex-range)) (let ((sortvar (sort ... ...))) (setq beg (car-safe (prog1 sortvar ...)) end (car-safe (prog1 sortvar ...)))) (setq this-command evil-ex-command) (run-hooks 'pre-command-hook) (set-mark end) (goto-char beg) (activate-mark) (call-interactively evil-ex-command) (run-hooks 'post-command-hook)))) (if (buffer-live-p buf) (progn (save-current-buffer (set-buffer buf) (deactivate-mark)))))
  (let ((buf (current-buffer))) (unwind-protect (cond ((not evil-ex-range) (setq this-command evil-ex-command) (run-hooks 'pre-command-hook) (call-interactively evil-ex-command) (run-hooks 'post-command-hook)) (t (let ((ex-range (evil-copy-range evil-ex-range)) beg end) (evil-expand-range ex-range) (setq beg (evil-range-beginning ex-range) end (evil-range-end ex-range)) (let ((sortvar ...)) (setq beg (car-safe ...) end (car-safe ...))) (setq this-command evil-ex-command) (run-hooks 'pre-command-hook) (set-mark end) (goto-char beg) (activate-mark) (call-interactively evil-ex-command) (run-hooks 'post-command-hook)))) (if (buffer-live-p buf) (progn (save-current-buffer (set-buffer buf) (deactivate-mark))))))
  (let* ((count (if (numberp range) (progn range))) (range (if (evil-range-p range) (progn range))) (bang (and (let ((save-match-data-internal (match-data))) (unwind-protect (progn (string-match ".!$" command)) (set-match-data save-match-data-internal 'evaporate))) t)) (evil-ex-point (point)) (evil-ex-range (or range (and count (evil-ex-range count count)))) (evil-ex-command (evil-ex-completed-binding command)) (evil-ex-bang (and bang t)) (evil-ex-argument (copy-sequence argument)) (evil-this-type (evil-type evil-ex-range)) (current-prefix-arg count) (prefix-arg current-prefix-arg)) (if (stringp evil-ex-argument) (progn (set-text-properties 0 (length evil-ex-argument) nil evil-ex-argument))) (let ((buf (current-buffer))) (unwind-protect (cond ((not evil-ex-range) (setq this-command evil-ex-command) (run-hooks 'pre-command-hook) (call-interactively evil-ex-command) (run-hooks 'post-command-hook)) (t (let ((ex-range ...) beg end) (evil-expand-range ex-range) (setq beg (evil-range-beginning ex-range) end (evil-range-end ex-range)) (let (...) (setq beg ... end ...)) (setq this-command evil-ex-command) (run-hooks 'pre-command-hook) (set-mark end) (goto-char beg) (activate-mark) (call-interactively evil-ex-command) (run-hooks 'post-command-hook)))) (if (buffer-live-p buf) (progn (save-current-buffer (set-buffer buf) (deactivate-mark)))))))
  evil-ex-call-command(nil #("vs" 0 1 (ex-index 1) 1 2 (ex-index 2)) nil)
  eval((evil-ex-call-command nil #("vs" 0 1 (ex-index 1) 1 2 (ex-index 2)) nil))
  (if evil-ex-expression (eval evil-ex-expression) (user-error "Ex: syntax error"))
  (if (= 0 (length result)) nil (if evil-ex-expression (eval evil-ex-expression) (user-error "Ex: syntax error")))
  evil-ex-execute(#("vs" 0 1 (ex-index 1) 1 2 (ex-index 2)))
  (let ((evil-ex-current-buffer (current-buffer)) (evil-ex-previous-command (if initial-input nil (car-safe evil-ex-history))) evil-ex-argument-handler evil-ex-info-string result) (let ((fun (if initial-input #'evil-ex-setup-and-update #'evil-ex-setup)) setup-hook) (setq setup-hook #'(lambda nil (remove-hook 'minibuffer-setup-hook setup-hook) (funcall fun))) (unwind-protect (progn (add-hook 'minibuffer-setup-hook setup-hook) (setq result (read-from-minibuffer ":" (or initial-input (and evil-ex-previous-command ...)) evil-ex-completion-map nil 'evil-ex-history evil-ex-previous-command t))) (remove-hook 'minibuffer-setup-hook setup-hook))) (evil-ex-execute result))
  evil-ex(nil)
  funcall-interactively(evil-ex nil)
  call-interactively(evil-ex nil nil)
  command-execute(evil-ex)
```

**Comment by joostkremers** [comment]
@hanschen Are you absolutely certain that you are using the latest version of `visual-fill-column`? Because in the latest version, the `min-margins` parameter is only ever set to `(0 . 0)` or to `nil`. So the value `(80 . 0)` that you see could not have been set by `visual-fill-column-mode`.

So if you are running the latest version, there is some other package setting `min-margins`, in which case we'd need to find out which package that is. Perhaps a work-around can be devised.

**Comment by hanschen** [comment]
@joostkremers Apparently I wasn't :facepalm:. After updating it works for me. Sorry for the noise.

**Comment by joostkremers** [comment]
@hanschen Glad to hear! :slightly_smiling_face:

**Comment by Atemu** [comment]
I haven't updated in a while so I'm still on the old version but if this happens to you in the future for some other reason, a quick workaround is to just toggle `visual-fill-column-mode`.
