### ISSUE TITLE
Obey line-move-visual

### ISSUE THREAD

**Issue by ThibautVerron** [joostkremers/visual-fill-column#5]
Hello,

When this mode is enabled, line movement does not seem to obey the value of `'line-move-visual` :  for example, `C-e` in a long paragraph with no hard newline will move to the end of the line, while with `visual-line-mode`, it would move to the end of the screen line (to the right margin).

**Comment by joostkremers** [comment]
If I understand the doc string of `line-move-visual` correctly, it does not affect the functioning of `C-a` and `C-e`, in only affects how the command `line-move` operates (which is called by `next-line` and `previous-line`, which appear behave correctly).

The Emacs manual seems to confirm this. Cf. the section “Visual Line Mode”:

> In Visual Line mode, some editing commands work on screen lines instead of logical lines: `C-a' (`beginning-of-visual-line') moves to the beginning of the screen line, `C-e' (`end-of-visual-line') moves to the end of the screen line, and `C-k' (`kill-visual-line') kills text to the end of the screen line.

It also tells you how to move by logical lines:

> To move by logical lines, use the commands `M-x next-logical-line' and `M-x previous-logical-line'. These move point to the next logical line and the previous logical line respectively, regardless of whether Visual Line mode is enabled. If you use these commands frequently, it may be convenient to assign key bindings to them.

**Comment by ThibautVerron** [comment]
Oh, damn, thank you, I guess I didn't read enough! 

But if this behavior is enabled by default with `visual-line-mode` (and not controlled by a variable), shouldn't `visual-fill-column` should enable the same behavior by default? Of course that's a design decision that's not mine to make, at least now I know how to get this behavior for myself.

By the way, for some reason `end-of-visual-line` with `visual-fill-column-mode` moves the point to the beginning of next line instead of the end of the current line. It is rather easy to work around (though I haven't given it much testing for the moment), but is it a bug?

**Comment by joostkremers** [comment]
> But if this behavior is enabled by default with `visual-line-mode` (and not controlled by a variable), shouldn't `visual-fill-column` should enable the same behavior by default? Of course that's a design decision that's not mine to make, at least now I know how to get this behavior for myself.

`visual-fill-column-mode` is an extension to `visual-line-mode`, not a replacement. Its intended use is to be activated together with `visual-line-mode`, so there shouldn’t be any need to reimplement its features.

> By the way, for some reason `end-of-visual-line` with `visual-fill-column-mode` moves the point to the beginning of next line instead of the end of the current line. It is rather easy to work around (though I haven't given it much testing for the moment), but is it a bug?

That could be a bug, though not necessarily one in `visual-fill-column`. `visual-fill-column-mode` is actually very simple, all it does is set the window margins to non-nil values so as to narrow the text area. If this leads to rendering problems, the bug is most likely in Emacs.

It would be helpful if you could construct a reproducible recipe to show the problem. Start with `emacs -Q` and used `M-x load-library` to load `visual-fill-column-mode`, then construct a text that shows the problem. Also include the version number in the output of `M-x emacs-version`.

**Comment by ThibautVerron** [comment]
Oh, I see, I misunderstood the documentation. Entirely my fault, looking back now, it is perfectly clear.

As for the `end-of-visual-line` issue, I cannot reproduce it even with the very same text I used yesterday and without `-Q`. So I guess that I will open another issue if it pops back. 

Thanks a lot, sorry for the useless report!

**Comment by joostkremers** [comment]
> Oh, I see, I misunderstood the documentation. Entirely my fault, looking back now, it is perfectly clear.

Do let me know if you feel I can improve something in the docs, though. If it is unclear to you, it is most likely unclear to others as well.

**Comment by joostkremers** [comment]
I changed the wording of the README a bit. Hopefully it's clearer now.
