### ISSUE TITLE
[Feature Request] Optionally wrap at a fixed column, regardless of the text scale

### ISSUE THREAD

**Issue by molok** [joostkremers/visual-fill-column#55]
I think it would be useful to many if visual-fill-column could optionally ignore the text-scale in its logic, this would achieve soft-wrapping lines at a fixed column (character-count), regardless of how big or small the characters are displayed.

**Comment by molok** [comment]
I just realized this is supposed to be the default behavior, it simply doesn't work with a non-default text-scaling because of a bug: #54

**Comment by joostkremers** [comment]
> I just realized this is supposed to be the default behavior, it simply doesn't work with a non-default text-scaling because of a bug: #54

What exactly do you mean by "non-default text-scaling"?
