### ISSUE TITLE
With `(global-visual-fill-column-mode)` using `M-x visual-line-mode` does not trigger the expected effect

### ISSUE THREAD

**Issue by wasamasa** [joostkremers/visual-fill-column#8]
1. Use `(global-visual-fill-column-mode)` in your init file
2. Open a file with overly long lines that would get wrapped by `visual-line-mode`
3. `M-x visual-line-mode`

I expect the lines to wrap around the value of `fill-column` (which is the standard of 70) in my case, a serialized lisp list. However, I only see the standard wrapping of `visual-line-mode`. Once I do a window configuration change, the wrapping changes to what I'd expect to see.

Using `edebug` revealed to me that at the time of using `turn-on-visual-fill-column-mode` the value of `visual-line-mode` is still `nil`. I'm using Emacs 24.4 on Arch Linux.

edit: I've worked around the bug for the time being by using `(add-hook 'visual-line-mode-hook 'visual-fill-column-mode)`. Wouldn't that be a viable alternative to having a globalized mode or at least, worth mentioning in the README?

edit 2: Apparently I've read too much into "To activate visual-fill-column-mode automatically in every buffer that uses visual-line-mode, customise the option global-visual-fill-column-mode or add the command (global-visual-fill-column-mode) to your init file." which I interpreted as "If you use `M-x visual-line-mode`, it will just work automatically!".  I've read the code again now and noticed that it doesn't directly interact with `visual-line-mode` at all. The bug behaviour I've described is its implementation. Anyways, would you mind adding a note to the README?

**Comment by joostkremers** [comment]
Yes, I should add a note to the README, it’s unclear the way it is now. But the behaviour you describe is exactly what is expected. `global-visual-fill-column-mode` only works if `visual-line-mode` is activated when a file is loaded, either by activating `global-visual-line-mode` or in a major mode hook. Otherwise, your alternative of adding `visual-fill-column-mode` to `visual-line-mode-hook` is the right approach.

**Comment by joostkremers** [comment]
Done. Thanks for reporting the issue.

**Comment by wasamasa** [comment]
Thanks!

**Comment by braham-snyder** [comment]
I'm not using `visual-line-mode` globally anymore, but when I was first testing it I was really tripped up by the fact that--for me at least--the following enables `visual-line-mode` globally, but not `visual-fill-column`:

```
(global-visual-line-mode)
(global-visual-fill-column-mode)
```

Counterintuitively, the reverse appears to work correctly. If this isn't particular to my configuration, it might be worth at least a mention in the README.

Thanks for the package!
